name: Laravel

on:
  push:
    branches:
      - main # The branch name you are committing the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Specify the PHP version you are using

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Specify the Node.js version you are using

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build # The build command of your Laravel project
